server:
  port: 11001
  servlet:
    context-path: /api
spring:
  devtools:
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
